export const slides = [
    {
        id:1,
        src:"images/1.jpg",
    },{
        id:2,
        src:"images/2.jpg",
    },{
        id:3,
        src:"images/3.jpg",
    },{
        id:4,
        src:"images/4.jpg",
    },{
        id:5,
        src:"images/5.jpg",
    },{
        id:6,
        src:"images/6.jpg",
    },{
        id:7,
        src:"images/7.jpg",
    },{
        id:8,
        src:"images/8.jpg",
    },{
        id:9,
        src:"images/9.jpg",
    },{
        id:10,
        src:"images/10.jpg",
    },{
        id:11,
        src:"images/11.jpg",
    },{
        id:12,
        src:"images/12.jpg",
    },{
        id:13,
        src:"images/herobg1.jpg",
    },{
        id:14,
        src:"images/herobg2.jpg",
    },{
        id:15,
        src:"images/15.jpeg",
    },
]